# Generated by Django 3.1.2 on 2020-10-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_data_type', models.CharField(db_index=True, max_length=255)),
                ('time_stamp', models.DateTimeField(db_index=True)),
                ('value', models.FloatField()),
            ],
        ),
    ]
