version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    hostname: kafka
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "${RAW_DATA_TOPIC_NAME}:1:1,${PARSED_DATA_TOPIC_NAME}:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  endpoint:
    build:
      context: ./endpoint
    ports:
      - "8000:5000"
    restart: always
    depends_on:
      - kafka
      - zookeeper
    volumes:
      - ./endpoint:/app
    env_file:
      - ./.env
  parser:
    build:
      context: ./parser
    restart: always
    depends_on:
      - kafka
      - zookeeper
      - endpoint
    volumes:
      - ./parser:/app
    env_file:
      - ./.env
  persister:
    build:
      context: ./persister
    restart: always
    depends_on:
      - kafka
      - zookeeper
      - parser
    volumes:
      - ./persister:/app
    env_file:
      - ./.env
